version: "3"
services:
  updater:
    build: .
    ports: 
      - "19781:8080"
    volumes:
      - "./device_deps.json:/app/device_deps.json"
      - "./devices.json:/app/devices.json"
      - "./devices_local.json:/app/devices_local.json"
    environment: 
      - UPSTREAM_URL=http://localhost/builds.json
      - DOWNLOAD_BASE_URL=http://localhost/builds
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:8.0.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data:
